set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)

set(
  ARM_GNU_TOOLCHAIN_BIN
  "/Applications/ArmGNUToolchain/15.2.rel1/arm-none-eabi/bin"
  CACHE PATH
  "Path to the Arm GNU Toolchain bin directory"
)

function(_find_tool out_var tool_name)
  if(ARM_GNU_TOOLCHAIN_BIN)
    find_program(_tool_path "${tool_name}" HINTS "${ARM_GNU_TOOLCHAIN_BIN}" NO_DEFAULT_PATH)
  endif()
  if(NOT _tool_path)
    find_program(_tool_path "${tool_name}")
  endif()
  if(NOT _tool_path)
    message(FATAL_ERROR "Unable to find ${tool_name}; set ARM_GNU_TOOLCHAIN_BIN to the toolchain bin directory")
  endif()
  set(${out_var} "${_tool_path}" PARENT_SCOPE)
endfunction()

_find_tool(_arm_cc arm-none-eabi-gcc)
_find_tool(_arm_cxx arm-none-eabi-g++)
_find_tool(_arm_objdump arm-none-eabi-objdump)
_find_tool(_arm_objcopy arm-none-eabi-objcopy)
_find_tool(_arm_size arm-none-eabi-size)
_find_tool(_arm_ar arm-none-eabi-ar)
_find_tool(_arm_ranlib arm-none-eabi-ranlib)

set(CMAKE_C_COMPILER "${_arm_cc}" CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER "${_arm_cxx}" CACHE FILEPATH "C++ compiler")
set(CMAKE_ASM_COMPILER "${_arm_cc}" CACHE FILEPATH "ASM compiler")
set(CMAKE_OBJDUMP "${_arm_objdump}" CACHE FILEPATH "objdump")
set(CMAKE_OBJCOPY "${_arm_objcopy}" CACHE FILEPATH "objcopy")
set(CMAKE_SIZE "${_arm_size}" CACHE FILEPATH "size")
set(CMAKE_AR "${_arm_ar}" CACHE FILEPATH "ar")
set(CMAKE_RANLIB "${_arm_ranlib}" CACHE FILEPATH "ranlib")
set(CMAKE_C_COMPILER_AR "${_arm_ar}" CACHE FILEPATH "C compiler archiver")
set(CMAKE_C_COMPILER_RANLIB "${_arm_ranlib}" CACHE FILEPATH "C compiler ranlib")
set(CMAKE_CXX_COMPILER_AR "${_arm_ar}" CACHE FILEPATH "CXX compiler archiver")
set(CMAKE_CXX_COMPILER_RANLIB "${_arm_ranlib}" CACHE FILEPATH "CXX compiler ranlib")
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_APPEND "<CMAKE_AR> q <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_APPEND "<CMAKE_AR> q <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
set(CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>\n<CMAKE_RANLIB> <TARGET>")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>\n<CMAKE_RANLIB> <TARGET>")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
